### PR TITLE
Black smefit

### PR DESCRIPTION
**Pull request by LucaMantani**
This PR simply reformats every file with black. It also adds a workflow that checks that files are correctly formatted with black. I think it would be a good idea to do this, uniforming the formatting of the code. It will also make the review of PRs easier because there will be no issue with formatting.

### CODE REVIEW

**Comment by LucaMantani** [comment]
That thing does not work for me... I have been able to push without it actually...

**Comment by LucaMantani** [comment]
@jacoterh I think it works now, I had to do 
```
pre-commit install
```

However, this is not currently enforced if someone works on the code it appears... How do we do?

**Comment by LucaMantani** [comment]
@jacoterh I removed the workflow, let's just make sure from now on that everyone committing to the repo has the precommit hooks working.

**Review by jacoterh — APPROVED** [review]
Thanks!

**Pull request merged**
