### PR TITLE
adding 2d projected CL contours

### PR DESCRIPTION
**Pull request by jacoterh**
Adding 2D projected confidence level contours functionality (both at the linear and quadratic level in the EFT expansion)

[report_example_NS.pdf](https://github.com/LHCfitNikhef/smefit_release/files/9646844/report_example_NS.pdf)

### CODE REVIEW

**Review by giacomomagni — COMMENTED** [review]
Okay looks good, before merging:
* can you list here they keys that you can add to the `report_runcard`, so we can easily remember them?
* Add `seaborn` to the `pyproject` dependencies, so test will pass again
* Did you check what happens if there are constrained coefficients? 
 This usually brings some further complications... If this is the case just plot the `free_dofs` as we do for the coefficients correlations. Even better you can pass an optional list of coefficients to display, so the figure do not blow up for large fits.
* Run black (or `pre-commit`) before merging.

**Comment by jacoterh** [comment]
Thanks Giacomo! The only extra key that I added to the report run card was `contours_2d` (boolean). Currently, this runcard is ignored, so it doesn't get pushed, so I wondered what's the best way to keep track of it.

**Comment by giacomomagni** [comment]
yes you are right, we need to add and runcard example. 
I was just lazy, but now it's the moment to do it. 
I'm trying to spell out as many as possible plotting options in the runcard, so this way we can maximise the report flexibility.

**Comment by jacoterh** [comment]
The analyse run card now supports 

`contours_2d:
    show: True
    confidence_level: 95
    dofs_show: Null # or list of op per fit to be displayed`
    
@giacomomagni Most tests have passes, except for codecov, what does this mean?

**Comment by giacomomagni** [comment]
> @giacomomagni Most tests have passed, except for codecov, what does this mean?

Thanks Jaco, I think you fixed all the items.
`codecov` is not passing because you are adding a feature without any test, so the test coverage is decreasing. 
If you have an easy test to add, to check that all the things are correct just add it in `tests/`, else no problem.
Testing plot features is not essential at the moment. 
Thanks for adding the runcard as well.

**Review by giacomomagni — APPROVED** [review]

**Pull request merged**
