### PR TITLE
Improve 2d contour plots

### PR DESCRIPTION
**Pull request by giacomomagni**
This PR is to address #48

### CODE REVIEW

**Comment by giacomomagni** [comment]
@jacoterh what do we do here? 
I don't have any strong opinion...

**Comment by jacoterh** [comment]
Looks good doesn't it? Seems like we can merge. Sorry I had completely forgotten about this PR

**Comment by giacomomagni** [comment]
Okay , if we want to keep it I'll try to clean it a bit. I recall there was a bit of code repetition...

**Comment by giacomomagni** [comment]
I'm happy to merge this. @jacoterh

**Pull request merged**
