### PR TITLE
[WIP] adding classmethod for Optimizer and removing config dependence

### PR DESCRIPTION
**Pull request by tgiani**
- add classmethod for Optimizer 
- removing config dependence from various functions
- modifying ```aggregate_coefficients``` function

### CODE REVIEW

**Comment by tgiani** [comment]
still work in progress

**Comment by tgiani** [comment]
@giacomomagni this should be ready for review

**Comment by giacomomagni** [comment]
I implemented some more changes. If you are are happy we can merge and go on rewriting the `CoeffTuple`

**Comment by tgiani** [comment]
yep I m happy with this, when you want go ahead with the merging

**Review by giacomomagni — APPROVED** [review]

**Pull request merged**
