### PR TITLE
HTML report

### PR DESCRIPTION
**Pull request by giacomomagni**
This PR is to introduce the HTML version of the report.
 
* [x] Add index to navigate in each content
* [x] Add recap table displaying the fit settings
* [x] Make all the tables style more consistent
* [x] Display all the on subpages such that it's easier to compare the result
* [x] Escape coefficient names correctly

### CODE REVIEW

**Comment by tgiani** [comment]
@giacomomagni can you commit here an example runcard?

**Comment by tgiani** [comment]
also, do you understand what s the problem with codcov?

**Comment by tgiani** [comment]
when running this the inks pointing to the different tables do not work for me, looks like it does not save the html tables in the meta folder

**Comment by giacomomagni** [comment]
Hi tommaso, this is now ready for review, It was a long battle with the HTML tables in the end you just need to install `pandoc` (`conda install pandoc`) and run it as usual.

**Comment by tgiani** [comment]
@giacomomagni  I ve tried this and it looks good! Can I merge it?

**Comment by giacomomagni** [comment]
yes

**Pull request merged**
