### PR TITLE
update version of pyyaml

### PR DESCRIPTION
**Pull request by tgiani**
this should fix the installation of the current main (which has still NS).
@giacomomagni @jacoterh could you please try to run `install.sh` and see if it works for you?

### CODE REVIEW

**Review by giacomomagni — APPROVED** [review]
Okay, it works.

**Comment by tgiani** [comment]
@giacomomagni thank you. Do you understand why the test are failing? Some test about the fisher is not passing, not sure what happened with that?

**Comment by giacomomagni** [comment]
> I don't remember as well, but they are failing also in master, so it's unrelated to this. I'm investigating it now.

Not sure why the fix was 61023e399b94346bcf3256c98e99a2a1672d1d1a, I'm not sure that test has any meaning ...

**Comment by tgiani** [comment]
thank you! uhm if the test is meaningless we can just remove it? A part from this I guess this can be merged?

**Comment by giacomomagni** [comment]
> thank you! uhm if the test is meaningless we can just remove it? A part from this I guess this can be merged?

Probably yes, but as long as it's passing let's keep it...

**Pull request merged**
